In [2]:
import numpy as np
import pandas as pd
import seaborn as sns


In [3]:
data = pd.read_csv("Diabetics_1.csv")

In [4]:
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [5]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
data.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [9]:
data.describe(include="all")

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [10]:
data.shape

(768, 9)

In [11]:
data.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [15]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [16]:
from sklearn.model_selection import train_test_split

In [24]:
data['Outcome']

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [26]:
X = data.drop('Outcome',axis = 1)


In [27]:
y = data['Outcome']

In [32]:
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=123)

In [35]:
from sklearn.tree import DecisionTreeClassifier

In [36]:
print(pd.value_counts(y_train,normalize=True)*100)

Outcome
0    66.480447
1    33.519553
Name: proportion, dtype: float64


In [37]:
print(pd.value_counts(y_test,normalize=True)*100)

Outcome
0    61.904762
1    38.095238
Name: proportion, dtype: float64


In [38]:
dtclf = DecisionTreeClassifier()

In [39]:
dtclf.fit(X_train,y_train)

DecisionTreeClassifier()

In [43]:
importances = dtclf.feature_importances_
importances

array([0.05715108, 0.26525514, 0.1045532 , 0.04554244, 0.07145295,
       0.16650491, 0.11861602, 0.17092427])

In [44]:
dtclf.classes_

array([0, 1], dtype=int64)

In [45]:
y_pred =dtclf.predict(X_test)

In [68]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score,classification_report

In [49]:
print("Confusion Matrix \n", confusion_matrix(y_pred,y_test))
print("Accurcay : ", accuracy_score(y_pred, y_test))
print("Recall   : ", recall_score(y_pred, y_test))
print("Precision: ", precision_score(y_pred, y_test)) 

Confusion Matrix 
 [[110  36]
 [ 33  52]]
Accurcay :  0.7012987012987013
Recall   :  0.611764705882353
Precision:  0.5909090909090909


#Hyper parameter tuning

In [61]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [62]:
dtclf1 = DecisionTreeClassifier()

In [63]:
#Define grid parameter
param_grid = {
    "criterion" : ["gini", "entropy"],
    "max_depth" : [2,3,4,5],
    "min_samples_split" : [2,4,6,8]
}

In [64]:
# applyin grid search cv
grid_search = GridSearchCV(
    estimator=dtclf1,
    param_grid=param_grid,
    cv =5
)

In [65]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 4, 5],
                         'min_samples_split': [2, 4, 6, 8]})

In [66]:
print("Best Parameters:", grid_search.best_params_)
best_model = grid_search.best_estimator_


Best Parameters: {'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 4}


In [83]:
# 9) Evaluate on test data
y_pred = best_model.predict(X_test)
print("Confusion Matrix \n", confusion_matrix(y_pred,y_test))
print("Accurcay : ", accuracy_score(y_pred, y_test))
print("Recall   : ", recall_score(y_pred, y_test))
print("Precision: ", precision_score(y_pred, y_test)) 
print("Classification Report:\n", classification_report(y_test, y_pred, target_names=["0","1"]))

Confusion Matrix 
 [[112  30]
 [ 31  58]]
Accurcay :  0.7359307359307359
Recall   :  0.651685393258427
Precision:  0.6590909090909091
Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.78      0.79       143
           1       0.65      0.66      0.66        88

    accuracy                           0.74       231
   macro avg       0.72      0.72      0.72       231
weighted avg       0.74      0.74      0.74       231



In [75]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)


In [76]:
X_train_res

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin        BMI  \
0              1       95             82             25      180  35.000000   
1              3      125             58              0        0  31.600000   
2              7      179             95             31        0  34.200000   
3             11      103             68             40        0  46.200000   
4              0      109             88             30        0  32.500000   
..           ...      ...            ...            ...      ...        ...   
709            7      144             71              0        0  32.633183   
710            3      139             68             41      255  42.171897   
711            5      111             76              0        0  34.766868   
712            1      170             67             47      572  41.714609   
713            1      127             48             44      193  40.430523   

     DiabetesPedigreeFunction  Age  
0                    0.233000   43  
1                    0.151000   24  
2                    0.164000   60  
3                    0.126000   42  
4                    0.855000   38  
..                        ...  ...  
709                  0.149569   44  
710                  0.461590   27  
711                  0.424545   27  
712                  0.689027   29  
713                  0.616655   24  

[714 rows x 8 columns]

In [77]:
print(pd.value_counts(y_train_res,normalize=True)*100)


Outcome
1    50.0
0    50.0
Name: proportion, dtype: float64


In [78]:
dtclf2 =DecisionTreeClassifier()

In [80]:
dtclf_sm = dtclf2.fit(X_train_res, y_train_res)

In [81]:
y_pred_sm = dtclf_sm.predict(X_test)

In [84]:
print("Confusion Matrix \n", confusion_matrix(y_pred_sm,y_test))
print("Accurcay : ", accuracy_score(y_pred_sm, y_test))
print("Recall   : ", recall_score(y_pred_sm, y_test))
print("Precision: ", precision_score(y_pred_sm, y_test)) 

Confusion Matrix 
 [[101  30]
 [ 42  58]]
Accurcay :  0.6883116883116883
Recall   :  0.58
Precision:  0.6590909090909091
